# =============================================================
# eval.yaml ― BLIP-2 / Surround360 평가 설정
#   • train_blip.py 로 훈련한 체크포인트를 로드해 COCO-evalcap
#     + CLIP 기반 지표를 계산합니다.
#   • test_surround360.py / eval_surround360.py 와 함께 사용하세요.
# =============================================================

# -----------------------------------------------------------------
# 1. 모델 설정
# -----------------------------------------------------------------
model:
  name: "surround"                         # "surround" | "blip2"
  pretrain_path: "saved_models/blip2_baseline"  # Stage-1/2 최고 체크포인트 경로
  num_query_tokens: 32                     # (선택) Q-Former 쿼리 토큰 수
  qformer:                                 # (선택) Q-Former 구성 오버라이드
    hidden_size: 768                       # 학습 당시 hidden 크기와 동일하게

# -----------------------------------------------------------------
# 2. 데이터 설정
# -----------------------------------------------------------------
data:
  dir: "data/quic360"                      # 이미지·CSV 위치
  test_file: "test.csv"                   # 평가용 CSV (url, query, annotation)
  max_length: 64                           # 텍스트 토큰 최대 길이
  image_size: [224, 224]                   # 모델 입력 크기 (H, W)
  do_crop: false                           # 파노라마 → FOV 크롭 여부
  fov: 90                                  # (크롭 사용 시) 시야각
  overlap_ratio: 0.5                       # (크롭 사용 시) 패치 간 중첩 비율

# -----------------------------------------------------------------
# 3. 생성 파라미터
# -----------------------------------------------------------------
generate:
  max_length: 32                           # max_new_tokens (출력 길이)
  num_beams: 5                             # Beam search 탐색 폭

# -----------------------------------------------------------------
# 4. 출력 파일
# -----------------------------------------------------------------
output:
  result_file: "results/surround360_eval.json"  # 전체 지표 + 상세 결과 저장 경로

# -----------------------------------------------------------------
# 5. 평가 설정
# -----------------------------------------------------------------
eval:
  batch_size: 8                            # GPU 1장 기준 권장
  num_workers: 4                           # DataLoader workers
  metrics: ["BLEU", "METEOR", "ROUGE", "CIDEr", "SPICE", "CLIP-S", "RefCLIP-S"]

# -----------------------------------------------------------------
# 6. 기타 옵션 (선택)
# -----------------------------------------------------------------
# device: "cuda"                           # CUDA / cpu 강제 지정 시 사용
