# config/eval.yaml 예시

# 1. 평가할 모델 정보
model:
  name: "surround" # 우리가 만든 SurroundBlip 모델을 사용하도록 지정
  # --- [매우 중요] 2단계 학습을 마친 최종 모델의 경로를 지정 ---
  pretrain_path: "./checkpoints/surroundblip_stage2_finetune"
  num_query_tokens: 32 # 학습 시와 동일한 설정
  qformer:
    num_hidden_layers: 12 # 학습 시와 동일한 설정

# 2. 평가 데이터 정보
data:
  dir: "./data/quic360"
  test_file: "test.csv" # 평가에 사용할 데이터 파일
  max_length: 32
  image_size: [224, 224]
  do_crop: True
  fov: 90.0
  overlap_ratio: 0.5

# 3. 생성(Inference) 관련 설정
generate:
  max_length: 128   # 생성할 문장의 최대 길이
  num_beams: 5      # 빔 서치(Beam Search) 크기

# 4. 평가 관련 설정
eval:
  batch_size: 16
  num_workers: 4
  # 평가할 지표 목록 (필요한 것만 남기거나 추가)
  metrics:
    - "BLEU"
    - "METEOR"
    - "ROUGE"
    - "CIDEr"
    - "SPICE"
    - "CLIP-S"
    - "RefCLIP-S"

# 5. 결과 파일 저장 경로
output:
  result_file: "./results/evaluation_results.json"

# 6. 사용할 디바이스
device: "cuda"