model:
    name: surround
    pretrain_path: "saved_models/surround_360_add_vicloss" # HuggingFace 형식으로 저장된 경로
data:
    dir: "data/quic360"
    test_file: "test.csv" # CSV: url,query,annotation
    image_size: [ 224, 224 ] # processor 에 전달 (필요시)
    max_length: 30 # 텍스트 토큰 최대 길이
    do_crop: true
    fov: 90
    overlap_ratio: 0.5
eval:
    batch_size: 16
    num_workers: 16
generate:
    max_length: 256
    num_beams: 5
device: "cuda"
output:
    result_file: "outputs/surround_360_add_vicloss_eval_results_long.json"
