wandb:
  project: "Surround360_2Stage"
  name: "stage1-vision_pretrain"

model:
  name: "surround"
  pretrain_name: "Salesforce/blip2-opt-2.7b" # 기본 BLIP-2 모델에서 시작
  num_query_tokens: 32
  qformer:
    num_hidden_layers: 12
  save_dir: "./checkpoints/surroundblip_stage1_vision_pretrain"

data:
  dir: "./data/quic360"
  train_file: "train.csv"
  valid_file: "valid.csv"
  max_length: 128
  image_size: [224, 224]
  do_crop: True
  fov: 90.0
  overlap_ratio: 0.5

training:
  output_dir: "./checkpoints/surroundblip_stage1_vision_pretrain"
  run_name: "stage1-vision_pretrain"
  num_epochs: 3 # Vision Pre-training은 보통 더 짧게
  learning_rate: 5.0e-5 # Vision Model 학습을 위한 learning rate
  batch_size:
    train: 16
    eval: 16
  gradient_accumulation_steps: 1
  logging_steps: 4 # 더 자주 로깅
  eval_strategy: "steps" # step 기반으로 변경
  eval_steps: 100 # 500 step마다 평가
  save_strategy: "steps" # step 기반 저장
  save_steps: 100
  save_total_limit: 3 # 최대 3개 체크포인트 유지
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss" # 최상의 모델 기준
  greater_is_better: false

  # 보고 설정
  report_to: "wandb"

  # 추가 최적화
  max_grad_norm: 1.0 # gradient clipping

deepspeed:
  enabled: false
  config: "config/ds_config_zero3.json"