wandb:
  project: "Surround360_2Stage"
  name: "stage2-instruction_finetune"

model:
  name: "surround"
  # --- [중요] 1단계에서 학습된 모델의 경로를 pretrain_name으로 지정 ---
  pretrain_name: "./checkpoints/surroundblip_stage1_vision_pretrain" 
  num_query_tokens: 32
  qformer:
    num_hidden_layers: 12
  save_dir: "./checkpoints/surroundblip_stage2_finetune"

data:
  dir: "./data/quic360"
  train_file: "train.csv"
  valid_file: "valid.csv"
  max_length: 512
  image_size: [224, 224]
  do_crop: True
  fov: 90.0
  overlap_ratio: 0.5
  # --- 2단계 학습 시 증강 비활성화 ---
  use_augmentation: False

training:
  output_dir: "./checkpoints/surroundblip_stage2_finetune"
  run_name: "stage2-instruction_finetune"
  num_epochs: 3
  learning_rate: 2.0e-5 # Fine-tuning을 위한 더 낮은 learning rate
  batch_size:
    train: 16
    eval: 16
  gradient_accumulation_steps: 1
  # ... 기타 설정
  report_to: "wandb"

deepspeed:
  enabled: false
  config: "config/ds_config_zero3.json"