# configs/stage1_vision_pretrain.yaml

stage_name: "vision_pretrain"

wandb:
  name: "stage1-vision_pretrain"

model:
  load_from_checkpoint: null # 처음부터 시작
  freeze_modules:
    - 'qformer'
    - 'language_projection'
    - 'language_model'
    - 'itm_head'

data:
  train_csv_path: "./data/quic360/train.csv"
  valid_csv_path: "./data/quic360/valid.csv"

training_args:
  output_dir: "./checkpoints/3stage_S1_vision"
  run_name: "3stage_S1_vision"
  num_train_epochs: 5
  learning_rate: 1e-4
  eval_steps: 500
  save_steps: 500
  loss_specific_args:
    overlap_consistency_weight: 1.0
