# config/train.yaml
wandb:
    project: "Surround360"
    name: "{model_name}"

model:
    name: "quic360-vlm" # 모델 이름 (경로 형식에 사용됨)
    vision_model_name: "facebook/dinov2-small" # 비전 모델
    llm_model_name: "Qwen/Qwen3-0.6B" # 언어 모델
    projector_type: "mlp2x_gelu" # 프로젝터 유형 (mlp, linear)
    use_resampler: true # 리샘플러 사용 여부
    mm_spatial_pool_mode: "average" # 공간 풀링 모드
    mm_newline_position: "grid" # 뉴라인 위치
    freeze_vision: true # 비전 모델 고정 여부
    freeze_llm: true # 언어 모델 고정 여부

dataset:
    train_csv: "data/quic360/train.csv" # 훈련 데이터 CSV 경로
    valid_csv: "data/quic360/valid.csv" # 검증 데이터 CSV 경로
    image_size: [ 224, 224 ] # 기본 이미지 크기
    max_length: 256 # 최대 토큰 길이
    do_crop: true # 360도 이미지 크롭 여부
    fov: 90.0 # 시야각 (Field of View), do_crop이 true일 때 사용
    overlap_ratio: 0.5 # 크롭 간 중첩 비율, do_crop이 true일 때 사용

training:
    train_itm: true # 훈련 ITM (Image-Text Matching) 여부
    output_dir: "outputs/{model_name}" # 출력 디렉토리
    run_name: "{model_name}-training" # 실행 이름
    logging_dir: "logs/{model_name}" # 로깅 디렉토리
    num_train_epochs: 3 # 훈련 에포크 수
    batch_size:
        train: 2 # 디바이스당 훈련 배치 크기
        eval: 2 # 디바이스당 평가 배치 크기
    gradient_accumulation_steps: 4 # 그래디언트 누적 단계
    learning_rate: 5e-5 # 학습률
    weight_decay: 0.01 # 가중치 감쇠
    warmup_ratio: 0.03 # 웜업 비율
    dataloader_num_workers: 8 # 데이터 로더 워커 수
    eval_strategy: "steps" # 평가 전략 (no, steps, epoch)
    eval_steps: 500 # 평가 단계 (eval_strategy가 steps일 때)
    save_strategy: "steps" # 저장 전략 (no, steps, epoch)
    save_steps: 500 # 저장 단계 (save_strategy가 steps일 때)
    save_total_limit: 3 # 저장할 총 체크포인트 수
    report_to: "wandb" # 보고 대상 (tensorboard, wandb 등)
    logging_steps: 100 # 로깅 단계
    max_grad_norm: 1.0 # 최대 그래디언트 노름

# DeepSpeed 설정 (선택 사항)
deepspeed:
    enabled: false # DeepSpeed 사용 여부
    config: "config/deepspeed_config.json" # DeepSpeed 설정 파일 경로
