# configs/stage2_qformer_pretrain.yaml

stage_name: "qformer_pretrain"

wandb:
  name: "stage2-qformer-pretrain"

model:
  # [중요] 1단계에서 저장된 체크포인트를 불러와서 학습을 이어감
  load_from_checkpoint: "./checkpoints/stage1_vision_pretrain/final_checkpoint"
  
  # Vision Encoder와 LLM은 고정하고 Q-Former 관련 모듈만 학습
  freeze_modules:
    - 'vision_model'
    - 'language_model'

data:
  train_csv_path: "./data/quic360/train.csv"
  valid_csv_path: "./data/quic360/valid.csv"
  # 캡션 길이에 맞게 max_length 조정
  max_length: 64

training_args:
  output_dir: "./checkpoints/stage2_qformer_pretrain"
  run_name: "stage2-qformer-pretrain"
  
  # 2단계에 적합한 하이퍼파라미터
  num_train_epochs: 5
  learning_rate: 1.0e-5
  
  eval_steps: 1000
  save_steps: 1000